travis:
  secure:
    BINSTAR_TOKEN: Hh88LykyE7Gnz9oJnJ2RtwamGN7MwUBAajqzrmtWUxRozZPOUaQ9REOAaI5rCuPCXSWJkzr6t9EHBJnlr54NrNKcmH9lG8nvlZ64wcIZkt/4MGDJ4mMdwFPwUsa6ICFOlvN0saysqomk18wd1bSi7tsTF5lXPOdWPpVzjjcUklNzQd6hNE7fdZiqrlP8lrW/D65AnKFel18WIWfwfMrTbL9185D2+B+MYcgBpLhgktCTWeTkQdc/zLLiBbOsnZlcsocwf/+pE4muMquzgJBr5ZiVHBNwrm5a4QqJgTyjlHL5E+uB5yrYVCmTf3WNo/lRkTBlzuiVPafCdlj/bTprqeItflv3l17nODHzDFlmT2ybYtPBFrCBpAg0aFt9MiJ2JZbFJS9o5owwPE8f8jAvdIivTgHt0W4Obs1h7dC0VW8UccI8qvM99g7FyOnLjnHVknnai0nEpOkoQkpzGSEmrTn6h9GhrDXCqrcfQYriZi0ChFf8shBbBuW29te8FuuPcoHo2nLjBkUWXZ0FpIyPjLP4y+ZEuKNo9qpLyxHGbSiyqZmlW/FqNrrKjmSyTk9BTOMlWmjIy7U2YOQ/NlRqnMYeErPVJPfz/qZmrOi6ZlmqXaQ8ML7sW7erE9LM8JPn96dqkHKcPM+GCvt1viy2MPFGwBzLZ7rcEiEsmAa7aUs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
